name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.kt'
      - '**.gradle.kts'
      - 'config/detekt.yml'
      - '.github/workflows/test-pr.yml'
      - 'gradle/libs.versions.toml'
      - 'gradle/wrapper/gradle-wrapper.properties'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**.kt'
      - '**.gradle.kts'
      - 'config/detekt.yml'
      - '.github/workflows/test.yml'
      - 'gradle/libs.versions.toml'
      - 'gradle/wrapper/gradle-wrapper.properties'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - run: ./gradlew detektAll
      - uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: lint-reports/kotlin/detekt.sarif
  test:
    name: Test / Wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew wasmJsBrowserTest --stacktrace
      - if: success() || failure()
        run: ./gradlew wasmJsBrowserTestReport --stacktrace
      - uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/wasmJsBrowserTest/TEST-*.xml'
      - uses: actions/upload-artifact@master
        if: success() || failure()
        with:
          name: all-wasm-js-test-reports
          path: ./build/reports/wasmJsBrowserTest
